### ISSUE TITLE
Bug: Timing Issues in TIM

### ISSUE THREAD

**Issue by omerday** [omerday/TIM-Task#24]
### Contact Details

Shir

### What happened?

According to Shir and Rany:

- [x] Time between fixation and first square is 7s (needs to be 4-6)
- [ ] Time between heat and rating is around 20s
- [x] Heat Pain event should be right when the heat arrives, and not 10s prior
- [ ] Full square should end right when the heat ends (See comment)
- [x] 5s between square and VAS
- [ ] One of the sides in the yellow square is missing??

### task

TIM

### Consistency

Consistent

**Comment by omerday** [comment]
>  Full square should end right when the heat ends

We remove the square after receiving confirmation from the MMS that it stopped successfully, and therefore, until changing the command logic, there's nothing that can be done to minimize that timing.

**Comment by omerday** [comment]
Waiting for the implementation of the new API
